on:
  pull_request:

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & Test
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Clean install of dependencies
      run: npm ci
    - name: Build application
      run: npm run build --if-present
    - name: Run test
      run: npm run test:prod
